/*
 * This source file was generated by the Gradle 'init' task
 */
package com.algebnaly.nfs4c

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {

    }
}
