/*
 * This source file was generated by the Gradle 'init' task
 */
package com.algebnaly.nfs4c

import java.net.URI
import kotlin.test.Test
import kotlin.test.assertEquals

class PathTest {
    @Test
    fun testPathNameCount() {
        val nfs4FileSystemProvider = NFS4FileSystemProvider()
        val nfS4FileSystem = NFS4FileSystem(
            nfs4Provider = nfs4FileSystemProvider,
            serverAddress = "",
            port = 2049,
            nfsClient = 0
        )
        val p1 = NFS4Path(nfS4FileSystem, "/")
        assertEquals(p1.nameCount, 0)
        val p2 = NFS4Path(nfS4FileSystem, "/a")
        assertEquals(p2.nameCount, 1)
        val p3 = NFS4Path(nfS4FileSystem, "/a/")
        assertEquals(p3.nameCount, 1)
        val p4 = NFS4Path(nfS4FileSystem, "/a/b/c/")
        assertEquals(p4.nameCount, 3)
    }
    @Test
    fun testParentPath(){
        val nfs4FileSystemProvider = NFS4FileSystemProvider()
        val nfS4FileSystem = NFS4FileSystem(
            nfs4Provider = nfs4FileSystemProvider,
            serverAddress = "",
            port = 2049,
            nfsClient = 0
        )
        val p1 = NFS4Path(nfS4FileSystem, "/")
        assertEquals(p1.parent, null)

        val p2 = NFS4Path(nfS4FileSystem, "")
        assertEquals(p2.parent, null)

        val p3 = NFS4Path(nfS4FileSystem, "/a")
        assertEquals(p3.parent?.toUri(), NFS4Path(nfS4FileSystem, "/").toAbsolutePath().toUri())

        val p4 = NFS4Path(nfS4FileSystem, "/a/b")
        assertEquals(p4.parent?.toUri(), NFS4Path(nfS4FileSystem, "/a").toAbsolutePath().toUri())
        val p5 = NFS4Path(nfS4FileSystem, "/a/b/")
        assertEquals(p5.parent?.toUri(), NFS4Path(nfS4FileSystem, "/a").toAbsolutePath().toUri())
    }
    @Test
    fun testPathToUri(){
        val nfs4FileSystemProvider = NFS4FileSystemProvider()
        val nfS4FileSystem = NFS4FileSystem(
            nfs4Provider = nfs4FileSystemProvider,
            serverAddress = "localhost",
            port = 2049,
            nfsClient = 0
        )
        val p1 = NFS4Path(nfS4FileSystem, "/")
        assertEquals(p1.toUri(), URI.create("nfs4://localhost:2049/"))
    }
}
